C-Learning: src/Programs/main_LanguageStandardCheck.cpp File Reference
main_LanguageStandardCheck.cpp File Reference
Standard check functions.
#include <Common.h>
#include <iostream>
#include <main_LanguageStandardCheck.h>
Functions
long getCPPStandard ()
Executes a check to determine and display the C++ language standard being used.
int execLanguageStandardCheck ()
Determines the C++ standard being used by the compiler.
Detailed Description
Standard check functions.
Author
JakaasJai69 (namde.nosp@m.omri.nosp@m.tunja.nosp@m.y@gm.nosp@m.ail.c.nosp@m.om)
Version
1.0
Date
2024-07-13
Copyright
Copyright (c) 2024
Definition in file main_LanguageStandardCheck.cpp.
Function Documentation
execLanguageStandardCheck()
int execLanguageStandardCheck ()
Determines the C++ standard being used by the compiler.
Returns
Always returns 0.
saves standard returned by gerCPPStandard()
Definition at line 44 of file main_LanguageStandardCheck.cpp.
{
  PLOGD
    << "[debug: execLanguageStandardCheck() is called.]\n";
  const int numStandards = 7;
  // The C++26 stdCode is a placeholder since the exact code won't be determined until the standard is finalized
  const long stdCode[numStandards] = {199711L,
                                      201103L,
                                      201402L,
                                      201703L,
                                      202002L,
                                      202302L,
                                      202612L};
  const char *stdName[numStandards] = {"Pre-C++11",
                                       "C++11",
                                       "C++14",
                                       "C++17",
                                       "C++20",
                                       "C++23",
                                       "C++26"};
  long standard = getCPPStandard();
  if (standard == -1)
  {
    std::cout << "Error: Unable to determine your language "
                 "standard.  Sorry.\n";
    return 0;
  }
  for (int i = 0; i < numStandards; ++i)
  {
    // If the reported version is one of the finalized standard codes
    // then we know exactly what version the compiler is running
    if (standard == stdCode[i])
    {
      std::cout << "Your compiler is using " << stdName[i]
                << " (language standard code " << standard
                << "L)\n";
      break;
    }
    // If the reported version is between two finalized standard codes,
    // this must be a preview / experimental support for the next upcoming version.
    if (standard < stdCode[i])
    {
      std::cout << "Your compiler is using a "
                   "preview/pre-release of "
                << stdName[i] << " (language standard code "
                << standard << "L)\n";
      break;
    }
  }
  return 0;
}
References getCPPStandard().
Referenced by execFunction().
getCPPStandard()
long getCPPStandard ()
Executes a check to determine and display the C++ language standard being used.
Returns
The C++ standard code as a long integer, or -1 if unable to determine.
Definition at line 22 of file main_LanguageStandardCheck.cpp.
{
  PLOGD << "[debug: getCPPStandard() is called.]\n";
  // Visual Studio is non-conforming in support for __cplusplus (unless you set a specific compiler flag, which you probably haven't)
  // In Visual Studio 2015 or newer we can use _MSVC_LANG instead
  // See https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/
#if defined(_MSVC_LANG)
  return _MSVC_LANG;
#elif defined(_MSC_VER)
  // If we're using an older version of Visual Studio, bail out
  return -1;
#else
  // __cplusplus is the intended way to query the language standard code (as defined by the language standards)
  return __cplusplus;
#endif
}
Referenced by execLanguageStandardCheck().