C-Learning: src/main_functions.cpp File Reference
main_functions.cpp File Reference
#include <Common.h>
#include <iostream>
#include <main_Calculator.h>
#include <main_Hello.h>
#include <main_LanguageStandardCheck.h>
#include <main_functions.h>
Functions
int selectFunction ()
Prompts the user to select a function and returns their choice.
int execFunction (int execCode)
Executes the function corresponding to the provided execution code.
Function Documentation
execFunction()
int execFunction (int execCode)
Executes the function corresponding to the provided execution code.
This function takes an execution code as input and calls the appropriate function based on that code.
Parameters
execCode An integer representing the function to execute: 1 for Calculator 2 for Hello Program 3 for Language Standard check
Returns
Always returns 0.
Definition at line 44 of file main_functions.cpp.
{
  switch (execCode)
  {
  case 1:
    execCalculator();
    break;
  case 2:
    execHello();
    break;
  case 3:
    execLanguageStandardCheck();
    break;
  }
  return 0;
}
References execCalculator(), execHello(), and execLanguageStandardCheck().
Referenced by main().
selectFunction()
int selectFunction ()
Prompts the user to select a function and returns their choice.
This function displays a menu of available functionalities and asks the user to input their choice. The user can choose between a calculator, a hello program, and a language standard check.
Returns
An integer representing the user's choice: 1 for Calculator 2 for Hello Program 3 for Language Standard check
Definition at line 20 of file main_functions.cpp.
{
  std::cout
    << "Enter the functionality you want:\n"
    << "1) Calculator (input 1 for first and so on) \n"
    << "2) Hello Program \n"
    << "3) Language Standard check \n";
  int funcNo{};
  std::cin >> funcNo;
  return funcNo;
}
Referenced by main().