name: ARM64 Cross-Compilation

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: uraimo/run-on-arch-action@v2
      name: Set arch and Build
      id: build
      with:
        arch: aarch64
        distro: ubuntu22.04
        githubToken: ${{ github.token }}

        setup: |
            mkdir -p "${PWD}/artifacts"

        dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"

        shell: /bin/sh

        install: |
          apt-get update -q
          apt-get install -y build-essential clang cmake
        run: |
          ls -la
          mkdir build
          cd build
          ls -la
          cmake -DCMAKE_BUILD_TYPE=Release ..
          ls -al
          cmake --build .
          ls -la
          mv main.out /artifacts/build-aarch64-main.out
          echo "Produced artifact at /artifacts/build-aarch64-main.out"
          cd /artifacts
          ls -la
          echo "changing permissions for cleanup"
          cd /home/runner/work/C-Learning/C-Learning/
          chmod -R a+rwx build


    - name: Checkout
      uses: actions/checkout@v4

    - name: Get the version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Release Build
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        generate_release_notes: true
        append_body: true
        body: "we have a bit of a problem here *cought*"
        name: Test-Releases-${{ steps.get_version.outputs.VERSION }}
        files: |
          "${PWD}/artifacts/build-aarch64-main.out"

