name: ARM64 Cross-Compilation

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: uraimo/run-on-arch-action@v2
      name: Set arch and Build
      id: build
      with:
        arch: aarch64
        distro: ubuntu22.04
        githubToken: ${{ github.token }}
        use_tini: true

        setup: |
            mkdir -p "${PWD}/artifacts"

        dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"

        shell: /bin/sh

        install: |
          apt-get update -q
          apt-get install -y build-essential clang cmake
        run: |
          ls -la
          mkdir build
          cd build
          ls -la
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .
          cp main.out /artifacts/
          echo "Produced artifact at /artifacts/main.out"
          echo "changing permissions for cleanup"
          cd /artifacts
          mv main.out build-aarch64-main.out
          cd /home/runner/work/C-Learning/C-Learning/
          chmod -R a+rwx build


    - name: Checkout
      uses: actions/checkout@v4

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

    - name: Release Build
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: Test-Releases-${{ steps.get_version.outputs.VERSION }}
        files: /artifacts/build-aarch64-main.out artifacts/build-aarch64-main.out
