name: Documentation

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build and publish documentation
    runs-on: [self-hosted, linux, ARM64]
    steps:

    - name: Install Doxygen
      run: echo 1 sudo -S apt-get install doxygen build-essentials -y

    - uses: actions/checkout@v4

    - name : Generate Docs
      run: doxygen

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
